name: "Multi event pipeline / workflow"

on:
  push:
    branches:
         - master
         - test
  pull_request:
    branches:
        - master


jobs:
    on-push: #job name, 1st job
        if: github.event_name == 'push' 
        runs-on: ubuntu-latest
        steps: #Steps to be executed in job
            - name: "Running on master/test push"
              run: echo "Running on master/test push"
    pull-request: #2nd job
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps: #Steps to execute in the job
            - name: "Running on pull request"
              run: echo "Running on pull request"


    on-workflow-dispatch: #3rd job, workflow dispatch is a trigger by which we can run workflow without a code push or pull request
         if: github.event_name == 'workflow_dispatch'
         runs-on: ubuntu-latest
         steps: #steps in this job
            - name: "Running on workflow dispatch"
              run: echo "Running on workflow dispatch"
