name: "Multi event pipeline / workflow"

on:
  push:
    branches:
         - master
         - test

  schedule:
         - cron: "0 10 * * 2,4" #cron is used to create the schedule for the pipeline to run on a specific day or the time
  pull_request:
    branches:
        - master
    types:
        - closed
        - opened

  workflow_dispatch:

jobs:
    on-push: #job name, 1st job
        if: github.event_name == 'push' 
        runs-on: ubuntu-latest
        steps: #Steps to be executed in job
            - name: "Running on master/test push"
              run: echo "Running on master/test push"
    pull-request: #2nd job
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps: #Steps to execute in the job
            - name: "Running on pull request"
              run: echo "Running on pull request"

    on_pull_request_opened:
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        runs-on: ubuntu-latest
        steps:
            - name: "Runs on pull request opened"
              run: echo "Running on pull request opened"

    on_pull_request_closed: #it will work when we close the PR on master branch itself, if we push through another branch we have to merge the pull request
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps: 
            - name: "Runs on pull request comes closed"
              run: echo "Running on pull request closed"


    on-workflow-dispatch: #3rd job, workflow dispatch is a trigger by which we can run workflow without a code push or pull request
         if: github.event_name == 'workflow_dispatch'
         runs-on: ubuntu-latest
         steps: #steps in this job
            - name: "Running on workflow dispatch"
              run: echo "Running on workflow dispatch"


    on-schedule:
         if: github.event_name == 'schedule'
         runs-on: ubuntu-latest
         steps:
            - name: "Running the pipeline on Tuesday and Thusday"
              run: echo "Running the pipeline/workflow on tuesday, thusday at 10:00"
